---

- name: "File {{ auto_upgrade_script }}"
  when: ansible_os_family == "Debian"
  ansible.builtin.copy:
    dest: "{{ auto_upgrade_script }}"
    src: "{{ role_path }}/templates/debian-auto-upgrade.sh"
    owner: root
    group: root
    mode: "0755"
