---

- name: Fail if operating system is not supported
  when: ansible_os_family not in ["Debian", "Archlinux"]
  ansible.builtin.fail:
    msg: "Operating system family not supported: {{ ansible_os_family }}"

- name: Delete /etc/cron.daily/60-auto-upgrade
  when: auto_upgrade_cron_script != "/etc/cron.daily/60-auto-upgrade"
  ansible.builtin.file:
    path: /etc/cron.daily/60-auto-upgrade
    state: absent

- name: File /etc/auto-upgrade.conf
  ansible.builtin.copy:
    dest: /etc/auto-upgrade.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      # Clean the packages in /var/cache/
      CLEAN_PACKAGES={{ '1' if auto_upgrade_clean else '0' }}

      {% if ansible_os_family == "Debian" -%}
      DEBIAN_APT_DIST_UPGRADE={{ '1' if auto_upgrade_debian_apt_dist_upgrade else '0' }}
      DEBIAN_APT_AUTOREMOVE={{ '1' if auto_upgrade_debian_apt_autoremove else '0' }}
      {% endif %}

- name: "File {{ auto_upgrade_cron_script }}"
  when: auto_upgrade_cron_script != "" and (ansible_os_family != "Debian" or not auto_upgrade_debian_unattended_upgrades | bool)
  ansible.builtin.copy:
    dest: "{{ auto_upgrade_cron_script }}"
    owner: root
    group: root
    mode: "0755"
    content: |
      #!/bin/sh
      exec {{ auto_upgrade_script }} >/dev/null

- name: Import Tasks from debian.yaml
  when: ansible_os_family == "Debian"
  ansible.builtin.import_tasks: "debian.yaml"

- name: Import Tasks from archlinux.yaml
  when: ansible_os_family == "Archlinux"
  ansible.builtin.import_tasks: "archlinux.yaml"
